Update type definitions for pg connection
knex/knex pull request #5139
Opened 2022-04-21 12:19 UTC by JoelVenable

Fixes #5124.

2022-04-21 17:11 UTC, OlivierCavadenti requested changes

2022-04-21 17:11 UTC, OlivierCavadenti commented on types/index.d.ts
> +  type PgGetTypeParser = (oid: number, format: string) => any
miss ";"

2022-05-22 12:06 UTC, kibertoad commented on types/index.d.ts
> +  type PgGetTypeParser = (oid: number, format: string) => any
```suggestion
  type PgGetTypeParser = (oid: number, format: string) => any;
```

2022-05-22 12:29 UTC, OlivierCavadenti approved these changes

2022-05-22 12:55 UTC, kibertoad approved these changes

2022-05-22 12:55 UTC, merged

2025-10-03 09:49 UTC, piotr-cz commented on types/index.d.ts
> +  type PgGetTypeParser = (oid: number, format: string) => any;
This is not valid anymore as function arguments are strongly typed now: https://github.com/brianc/node-pg-types/blob/d9d9dfb87eb50914043cbc178c301b7dd3b0c50d/index.d.ts#L135