Fixes unexpected max acquire-timeout
knex/knex pull request #5377
Opened 2022-11-11 01:53 UTC by MattGson

Important for applications where high pool contention is expected, and completion is favored over latency.

2022-11-11 04:01 UTC, MattGson commented
Failing for a js-doc linter but I have not touched any js-doc...


```
The 'no-redundant-jsdoc' rule threw an error in '/home/runner/work/knex/knex/types/index.d.ts':
Error: Unexpected tag kind: JSDocDeprecatedTag
    at checkTag (/home/runner/work/knex/knex/node_modules/tslint/lib/rules/noRedundantJsdocRule.js:105:23)
    at cb (/home/runner/work/knex/knex/node_modules/tslint/lib/rules/noRedundantJsdocRule.js:[62](https://github.com/knex/knex/actions/runs/3442216445/jobs/5742565292#step:5:63):25)
    at visitNodes (/home/runner/work/knex/knex/node_modules/typescript/lib/typescript.js:31095:30)
    at Object.forEachChild (/home/runner/work/knex/knex/node_modules/typescript/lib/typescript.js:31502:21)
    at cb (/home/runner/work/knex/knex/node_modules/tslint/lib/rules/noRedundantJsdocRule.js:67:19)
    at visitNodes (/home/runner/work/knex/knex/node_modules/typescript/lib/typescript.js:31095:30)
    at Object.forEachChild (/home/runner/work/knex/knex/node_modules/typescript/lib/typescript.js:31421:24)
    at cb (/home/runner/work/knex/knex/node_modules/tslint/lib/rules/noRedundantJsdocRule.js:[67](https://github.com/knex/knex/actions/runs/3442216445/jobs/5742565292#step:5:68):19)
    at visitNode (/home/runner/work/knex/knex/node_modules/typescript/lib/typescript.js:31086:24)
    at Object.forEachChild (/home/runner/work/knex/knex/node_modules/typescript/lib/typescript.js:31521:21)
```

2022-11-14 13:11 UTC, OlivierCavadenti requested changes
The error is here : 

/home/runner/work/knex/knex/lib/client.js
  216:39  error  Parsing error: Identifier directly after number

2022-11-17 03:28 UTC, MattGson commented
> 



> The error is here :
> 
> /home/runner/work/knex/knex/lib/client.js 216:39 error Parsing error: Identifier directly after number

Ah, looks like the linter doesn't like [numeric-separators](https://v8.dev/features/numeric-separators)

2022-11-17 08:53 UTC, OlivierCavadenti approved these changes

2022-11-17 08:53 UTC, merged