Add uuid helper function
knex/knex pull request #5617
Opened 2023-07-01 21:11 UTC by arbezerra

Meant to be used in the schema creation:
```javascript
await knex.schema
    .createTable('users', table => {
      table.uuid('id').defaultTo(knex.fn.uuid());
      table.string('user_name');
    })
```

Can someone confirm that there is no uuid function in Redshift?

2023-07-04 08:09 UTC, OlivierCavadenti requested changes
It's not easy in Amazon Redshift unfortunaly:
http://datasamurai.blogspot.com/2016/06/creating-uuid-function-in-redshift.html

2023-07-04 08:09 UTC, OlivierCavadenti commented on test/integration2/query/misc/additional.spec.js
> +          );
Can you add cases that test the piece of query generated for each dialect ?

2023-07-07 05:57 UTC, arbezerra commented
The coverage decreased because oracle and redshift aren't tested. Should I make a test to cover those lines or put a comment to ignore coverage?

2023-07-07 07:43 UTC, OlivierCavadenti commented
> The coverage decreased because oracle and redshift aren't tested. Should I make a test to cover those lines or put a comment to ignore coverage?

Can you add test for OracleDB (same that Oracle) and for Redshift that test that the uuid function throw an Error with "Redshift does not have a uuid function" and it's seems good !

Can you also add a documentation ? 
https://github.com/knex/documentation

2023-07-07 17:43 UTC, arbezerra commented
I think everything is ok now.
Opened PR knex/documentation#527

2023-07-08 12:54 UTC, OlivierCavadenti approved these changes

2023-07-08 12:54 UTC, merged