Fix knex d.ts to work with mixed modules
knex/knex pull request #5659
Opened 2023-08-12 19:21 UTC by patrickshipe

Currently, the knex type declarations use `export default` as if it were an ES module. This has not mattered up until recently with Node's increased ESM support and TypeScript's `node16` module setting.

Bear with me - this is a bit convoluted. Node's behavior when importing CJS from an ES module is to make `module.exports` the default export. TypeScript follows this behavior, which leads to some weird quirks when we look at knex's type declarations. TS knows detects knex as a CJS module, and when it sees a default export in the declarations, it assumes that the `knex` function is set to `module.exports.default` (which it _also_ is) but _not_ to `module.exports`.  So to TS, under `node16` module mode, the default export from knex is simply an object with a `default` property. It cannot be called as a function, even though in reality it can.

What's the fix here? It's quite simple. Use `export =` syntax to describe the CJS export. This works perfectly in both the new world and old.

2023-08-28 22:18 UTC, patrickshipe commented
@OlivierCavadenti - would really appreciate a look at this one. The TypeScript team is really pushing Node users to move to module `node16` and the current typings make this very difficult. Let me know what else I can do to help!

2023-08-28 22:20 UTC, patrickshipe commented
https://arethetypeswrong.github.io/?p=knex%402.5.1

<img width="775" alt="image" src="https://github.com/knex/knex/assets/42809110/fa70da01-c575-4343-b40d-b683aef4371c">

2023-09-11 13:29 UTC, kibertoad requested changes
Thanks! Is it possible to add additional tests which would have been failing under old setup?

2023-09-11 13:46 UTC, patrickshipe commented
@kibertoad I have not found a way to configure the type definition testing tool to test using module node16/nodenext in addition to the current settings. The tool seems to only allow for one tsconfig configuration in the package.json. If someone has a way to do this I am happy to give it a shot.

2023-09-11 13:51 UTC, merged

2023-10-02 09:41 UTC, valtlai commented
Is there plans to release a new patch version soon that includes this fix?

2023-10-04 18:04 UTC, patrickshipe commented
@kibertoad will this be published this week? Thank you :)

2023-10-05 16:08 UTC, Jiralite commented
Does this not resolve #5358?

2023-10-05 16:39 UTC, patrickshipe commented
It does @Jiralite ! We need a new version published with this code though.

2023-10-05 16:40 UTC, Jiralite commented
Awesome. Yeah, I was more pointing out that issue should ideally be closed then.

2023-10-06 06:56 UTC, kibertoad commented
Sorry for the delay. 3.0.0 is now out! Please let me know if it works as expected.

2023-10-06 11:54 UTC, valtlai commented
@kibertoad Thank you, it’s now working as expected.